name: dualarim
description: This is hwconsultant Flutter Project. This app is for Muslim.
version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^0.1.2
  shared_preferences: ^0.5.6+3
  provider: ^3.0.0
  flutter_launcher_icons: ^0.7.4
  intl: ^0.16.1
  firebase_remote_config: ^0.3.0+3
  json_annotation: ^2.4.0
  build_runner: ^1.6.1
  json_serializable: ^3.0.0
  flutter_bloc: ^0.20.0
  equatable: ^0.3.0
  catcher: ^0.3.2

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter_icons:
  image_path: "assets/icons/icon.png" 
  android: true
  ios: true

flutter:

  uses-material-design: true

  assets:
   - assets/imgs/
   - assets/icons/

  fonts:
    - family: Lato
      fonts:
        - asset: assets/fonts/lato/Lato-Regular.ttf
        - asset: assets/fonts/lato/Lato-Italic.ttf
          style: italic
        - asset: assets/fonts/lato/Lato-Bold.ttf
          weight: 700